
# Amazon S3
AMAZON_BUCKET_NAME: ''
AMAZON_KEY_ID: ''
AMAZON_ACCESS_KEY: ''
AMAZON_REGION: ''


OFFICE_NAME : 'ESCALA'
LOGO_URL : 'logo.gif'
LOGO_URL_NAME : 'logo-escala.gif'

# Social media
FACEBOOK_LINK : ''
PINTEREST_LINK : ''
INSTAGRAM_LINK : ''
TWITTER_LINK : ''
GOOGLE_PLUS_LINK : ''
VIMEO_LINK : ''



